package com.montunosoftware.pillpopper.database;

import com.montunosoftware.pillpopper.android.util.PillpopperConstants;

public class DatabaseConstants {

	/** Queries to create the Database **/

	public static final String DROP_TABLE_PILL_QUERY = "DROP TABLE IF EXISTS PILL;";
	public static final String DROP_TABLE_USER_PREFERENCE_QUERY = "DROP TABLE IF EXISTS USERPREFERENCE;";
	public static final String DROP_TABLE_PILL_PREFERENCE_QUERY = "DROP TABLE IF EXISTS PILLPREFERENCE;";
	public static final String DROP_TABLE_USER_QUERY = "DROP TABLE IF EXISTS USER ;";
	public static final String DROP_TABLE_PILL_SCHEDULE = "DROP TABLE IF EXISTS PILL_SCHEDULE ;";
	public static final String DROP_TABLE_PILL_HISTORY = "DROP TABLE IF EXISTS PILL_HISTORY ;";
	public static final String DROP_TABLE_LOG_ENTRY = "DROP TABLE IF EXISTS LOG_ENTRY ;";
	public static final String DROP_TABLE_USER_REMINDERS_QUERY = "DROP TABLE IF EXISTS USERREMINDERS;";
	public static final String DROP_TABLE_LATE_REMINDERS_QUERY = "DROP TABLE IF EXISTS PASTREMINDERS;";
	public static final String DROP_TABLE_PENDING_IMAGE_SYNC_REQUESTS = "DROP TABLE IF EXISTS PendingImageSyncRequests;";
	public static final String DROP_TABLE_IMAGE_FAILURE_ENTRIES = "DROP TABLE IF EXISTS IMAGE_FAILURE_ENTRIES";
	public static final String DROP_TABLE_HISTORY_PREFERENCE_QUERY = "DROP TABLE IF EXISTS HISTORY_PREFERENCE";


	// Create Table Queries
	// if there is any change in any TABLE schema, handle database onUpgrade Scenario.
	// write appropriate alter table queries which should be called from each version going upwards from 3.4
	public static final String CREATE_TABLE_PILL_QUERY = "CREATE TABLE IF NOT EXISTS PILL (_id integer primary key, PILLID VARCHAR(300) unique, USERID VARCHAR(300), PILLNAME VARCHAR(300), CREATED VARCHAR(300), DAYPERIOD VARCHAR(300), DOSE VARCHAR(300), NUMPILLS VARCHAR(300), INSTRUCTION VARCHAR(300), HASUNDO VARCHAR(300), LAST_TAKEN VARCHAR(300), EFFLASTTAKEN VARCHAR(300), NEXT VARCHAR(300), OVERDUE VARCHAR(300), START VARCHAR(300), END VARCHAR(300), NOTIFYAFTER VARCHAR(300), TAKEPILLAFTER VARCHAR(300), SKIPPILLAFTER VARCHAR(300), MAXPOSTPONETIME VARCHAR(300), SERVEREDITTIME VARCHAR(300), SERVEREDITGUID VARCHAR(300), INSTRUCTIONS VARCHAR(300), INTERVAL VARCHAR(300), NOTIFYAFTER_TZSECS VARCHAR(300),LAST_TAKEN_TZSECS VARCHAR(300), EFFLASTTAKEN_TZSECS VARCHAR(300), SCHEDULE_GUID VARCHAR(200));";
	public static final String CREATE_TABLE_USER_PREFERENCE_QUERY = "CREATE TABLE IF NOT EXISTS USERPREFERENCE (_id integer primary key, USERID VARCHAR(300), APPINSTALLED VARCHAR(300), BEDTIMESTART VARCHAR(300) , BEDTIMEEND VARCHAR(300), CREATED VARCHAR(300), ARCHIEVEDDRUGDISPLAYED VARCHAR(300), CUSTOMDRUGDOSAGENAMECOUNT VARCHAR(300), DOSEHISTORYDAYS VARCHAR(300), DRUGSORTORDER VARCHAR(300), DSTOFFSETSECS VARCHAR(300), EARLYDOSEWARNING VARCHAR(300), LASTDOSEPERIODSECS VARCHAR(300), PERSONNAMESCOUNT VARCHAR(300), POSTPONESDISPLAYED VARCHAR(300), PRIVACYMODE VARCHAR(300), QUICKVIEWOPTINED VARCHAR(300), REMINDERSOUNDFILENAME VARCHAR(300), SECONDARYREMINDERPERIODSECS VARCHAR(300), TZNAME VARCHAR(300), TZSECS VARCHAR(300), STARTEDLAZYSERVERUPDATES VARCHAR(300), SUBSCRIPTIONTYPE VARCHAR(300), LATEDOSEPERIODSECS VARCHAR(300), ANDROIDREMINDERSOUNDFILENAME VARCHAR(300));";
	public static final String CREATE_TABLE_PILL_PREFERENCE_QUERY = "CREATE TABLE IF NOT EXISTS PILLPREFERENCE (_id integer primary key, PILLID VARCHAR(300) REFERENCES PILL(PILLID) ON DELETE CASCADE, ARCHIVED VARCHAR(300), CUSTOMDESCRIPTION VARCHAR(300), CUSTOMDOSAGEID VARCHAR(300), DOCTORCOUNT VARCHAR(300), IMAGEGUID VARCHAR(300), INVISIBLE VARCHAR(300), LOGMISSEDDOSES VARCHAR(300), MISSEDDOSESLASTCHECKED VARCHAR(300), NOPUSH VARCHAR(300), NOTES VARCHAR(300), PERSONID VARCHAR(300), PHARMACYCOUNT VARCHAR(300), PRESCRIPTIONNUM VARCHAR(300), REFILLALERTDOSES VARCHAR(300), REFILLSREMAINING VARCHAR(300), REMAININGQUANTITY VARCHAR(300), SECONDARYREMINDERS VARCHAR(300), WEEKDAYS VARCHAR(300), lastManagedIdNotified VARCHAR(300), lastManagedIdNeedingNotify VARCHAR(300), dosageType VARCHAR(300), maxNumDailyDoses VARCHAR(300), databaseNDC VARCHAR(300), managedDropped VARCHAR(300), managedMedicationId VARCHAR(300) , managedDescription VARCHAR(300), databaseMedFormType VARCHAR(300), DELETED VARCHAR(300),limitType VARCHAR(300), scheduledFrequency VARCHAR(300), MISSEDDOSESLASTCHECKED_TZSECS VARCHAR(300), SCHEDULEDATECHANGED_TZSECS VARCHAR(300), defaultImageChoice VARCHAR(300), defaultServiceImageID VARCHAR(300) , needFDBUpdate VARCHAR(25) , scheduleChoice VARCHAR(20));";
	public static final String CREATE_TABLE_USER_QUERY = "CREATE TABLE IF NOT EXISTS USER (_id integer primary key, USERID VARCHAR(300) , USERTYPE VARCHAR(300), RELATIONDESC VARCHAR(300), RELID VARCHAR(300), ENABLED VARCHAR(300), NICKNAME VARCHAR(300), DISPLAYNAME VARCHAR(300), FIRSTNAME VARCHAR(300), LASTNAME VARCHAR(300), MIDDLENAME VARCHAR(300), LASTSYNCTOKEN VARCHAR(300), HASCHANGES BOOLEAN DEFAULT 1, MRN VARCHAR(300), GENDER VARCHAR(300),AGE VARCHAR(300), ISTEEN BOOLEAN, ISTEENTOGGLEENABLED BOOLEAN);";
	public static final String CREATE_TABLE_PILL_SCHEDULE = "CREATE TABLE IF NOT EXISTS PILL_SCHEDULE (_id integer primary key, PILLID VARCHAR(300) REFERENCES PILL(PILLID) ON DELETE CASCADE, PILLTIME VARCHAR(300));";
	public static final String CREATE_TABLE_PILL_HISTORY = "CREATE TABLE IF NOT EXISTS PILL_HISTORY (_id integer primary key, PILLID VARCHAR(300) ,PILLNAME VARCHAR(300),CUSTOMDESCRIPTION VARCHAR(300),tz_secs VARCHAR(100),tz_name VARCHAR(300),dosageType VARCHAR(300), managedDescription VARCHAR(300), OPID VARCHAR(300), DELETED VARCHAR(300), GUID VARCHAR(300), UPDATEUSERID VARCHAR(300), CREATIONDATE VARCHAR(300), OPERATION VARCHAR(300), EVENTDESCRIPTION VARCHAR(300), SCHEDULEDATE VARCHAR(300), EDITTIME VARCHAR(300), PERSONID VARCHAR(300), OPERATIONDATA VARCHAR(300), CREATEUSERID VARCHAR(300));";
	public static final String CREATE_TABLE_LOG_ENTRY = "CREATE TABLE IF NOT EXISTS LOG_ENTRY (_id integer primary key, DATEADDED TEXT, ENTRY TEXT, GUID TEXT, LASTUPLOADATTEMPT TEXT, LASTUPLOADRESPONSE TEXT, ACTION INTEGER);";
	public static final String CREATE_TABLE_USER_REMINDERS_QUERY = "CREATE TABLE IF NOT EXISTS USERREMINDERS (_id integer primary key, USERID VARCHAR(300), REMINDERS VARCHAR(300));";
	public static final String CREATE_TABLE_LATE_REMINDERS_QUERY = "CREATE TABLE IF NOT EXISTS PASTREMINDERS (_id integer primary key, PILLID VARCHAR(300) REFERENCES PILL(PILLID) ON DELETE CASCADE, PILLTIME VARCHAR(300));";
	public static final String CREATE_TABLE_PENDING_IMAGE_SYNC_REQUESTS = "CREATE TABLE IF NOT EXISTS PENDINGIMAGESYNCREQUESTS (_id integer primary key, PILLID VARCHAR(300), IMAGEGUID VARCHAR(300), NEEDSUPLOAD INTEGER, NEEDSDELETE INTEGER);";
	public static final String CREATE_TABLE_FDB_IMAGE = "CREATE TABLE IF NOT EXISTS FDBIMAGE (_id integer primary key, PILLID VARCHAR(300), isCurrent VARCHAR(300), imageID VARCHAR(300), startDate VARCHAR(300), endDate VARCHAR(300), imageDesc VARCHAR(300), imageData BLOB);";
	public static final String CREATE_TABLE_CUSTOM_IMAGE = "CREATE TABLE IF NOT EXISTS CUSTOMIMAGE (_id integer primary key, PILLID VARCHAR(300), imageID VARCHAR(300), imageDesc VARCHAR(300), imageData BLOB);";
	public static final String CREATE_TABLE_IMAGE_FAILURE_ENTRIES = "CREATE TABLE IF NOT EXISTS IMAGE_FAILURE_ENTRIES(_id integer primary key, PILLID VARCHAR(300) REFERENCES PILL(PILLID) ON DELETE CASCADE, IMAGEID VARCHAR(300), TYPE VARCHAR(300));";
	public static final String CREATE_TABLE_HISTORY_PREFERENCES = "CREATE TABLE IF NOT EXISTS HISTORY_PREFERENCE (_id integer primary key, GUID VARCHAR(300), startDate varchar(100), endDate varchar(100), scheduleDate varchar(100), scheduleFrequency varchar(100), dayPeriod varchar(100), weekdays varchar(100), scheduleChoice varchar(100), " +
			"customDescription VARCHAR(300), managedDescription VARCHAR(300), dosageType varchar(100), isPostponedEventActive BOOLEAN, finalPostponedDateTime varchar(100), actionDate varchar(100), recordDate varchar(100), scheduleGuid varchar(200))";

	// FDBImage Table Fields
	public static final String FDB_PILL_ID = "PILLID";
	public static final String FDB_IMAGE_ID = "imageID";
	public static final String FDB_IMAGE_DATA = "imageData";

	// CUSTOMImage Table Fields
	public static final String CUSTOM_IMAGE_ID = "imageID";
	public static final String CUSTOM_IMAGE_DATA = "imageData";


	///USER TABLE FIELD//////

	public static final String USER_ID = "USERID";
	public static final String LAST_SYNC_TOKEN = "LASTSYNCTOKEN";
	public static final String USER_TYPE = "USERTYPE";
	public static final String RELATION_DESC = "RELATIONDESC";
	public static final String REL_ID = "RELID";
	public static final String ENABLED = "ENABLED";
	public static final String NICK_NAME = "NICKNAME";
	public static final String DISPLAY_NAME = "DISPLAYNAME";
	public static final String FIRST_NAME = "FIRSTNAME";
	public static final String LAST_NAME = "LASTNAME";
	public static final String MIDDLE_NAME = "MIDDLENAME";
	public static final String HAS_CHANGES = "HASCHANGES";
	public static final String MRN = "MRN";
	public static final String GENDER = "GENDER";
	public static final String AGE = "AGE";
	public static final String ISTEEN = "ISTEEN";
	public static final String ISTEEN_TOGGLE_ENABLED = "ISTEENTOGGLEENABLED";

	//User Reminders Table
	public static final String REMINDERS_ENABLED = "REMINDERS";

	// USER PREFERENCE TABLE Fields
	public static final String USER_PREFERNECE_USER_ID = "USERID";
	public static final String BEDTIME_END = "BEDTIMEEND";
	public static final String BEDTIME_START = "BEDTIMESTART";
	public static final String USER_PREFERENCE_CREATED = "CREATED";
	public static final String ARCHIEVED_DRUG_DISPLAYED = "ARCHIEVEDDRUGDISPLAYED";
	public static final String CUSTOM_DRUG_DOSAGE_NAME_COUNT = "CUSTOMDRUGDOSAGENAMECOUNT";
	public static final String DOSE_HISTORY_DAYS = "DOSEHISTORYDAYS";
	public static final String DRUG_SORT_ORDER = "DRUGSORTORDER";
	public static final String DST_OFFSET_SECS = "DSTOFFSETSECS";
	public static final String EARLY_DOSE_WARNING = "EARLYDOSEWARNING";
	public static final String LATE_DOSE_PERIOD_SECS = "LATEDOSEPERIODSECS";
	public static final String PERSON_NAMES_COUNT = "PERSONNAMESCOUNT";
	public static final String POSTPONES_DISPLAYED = "POSTPONESDISPLAYED";
	public static final String PRIVACY_MODE = "PRIVACYMODE";
	public static final String QUICKVIEW_OPTINED = "QUICKVIEWOPTINED";
	public static final String REMINDER_SOUND_FILENAME = "REMINDERSOUNDFILENAME";
	public static final String SECONDARY_REMINDER_PERIOD_SECS = "SECONDARYREMINDERPERIODSECS";
	public static final String TZ_NAME= "TZNAME";
	public static final String TZ_SECS = "TZSECS";
	public static final String SUBSCRIPTION_TYPE= "SUBSCRIPTIONTYPE";
	public static final String ANDROID_REMINDER_SOUND_FILENAME= "ANDROIDREMINDERSOUNDFILENAME";

	// PILL TABLE FIELDS
	public static final String PILL_ID = "PILLID";
	public static final String PILL_USER_ID = "USERID";
	public static final String PILL_NAME = "PILLNAME";
	public static final String CREATED = "CREATED";
	public static final String DAY_PERIOD = "DAYPERIOD";
	public static final String DOSE = "DOSE";
	public static final String NUM_PILLS = "NUMPILLS";
	public static final String INSTRUCTIONS = "INSTRUCTION";
	public static final String HAS_UNDO = "HASUNDO";
	public static final String LAST_TAKEN = "LAST_TAKEN";
	public static final String EFF_LAST_TAKEN = "EFFLASTTAKEN";
	public static final String LAST_TAKEN_TZSECS = "LAST_TAKEN_TZSECS";
	public static final String EFF_LAST_TAKEN_TZSECS = "EFFLASTTAKEN_TZSECS";
	public static final String NEXT = "NEXT";
	public static final String OVERDUE = "OVERDUE";
	public static final String START = "START";
	public static final String END = "END";
	public static final String TAKE_PILL_AFTER = "TAKEPILLAFTER";
	public static final String SKIP_PILL_AFTER = "SKIPPILLAFTER";
	public static final String MAX_POSTPONE_TIME= "MAXPOSTPONETIME";
	public static final String SERVER_EDIT_TIME = "SERVEREDITTIME";
	public static final String SERVER_EDIT_GUID = "SERVEREDITGUID";
	public static final String NOTIFY_AFTER = "NOTIFYAFTER";
	public static final String NOTIFY_AFTER_TZSECS = "NOTIFYAFTER_TZSECS";
	public static final String INTERVAL = "INTERVAL";
	public static final String SCHEDULE_GUID = "SCHEDULE_GUID";


	// PILL PREFERNCE TABLE FIELD

	//public static final String PILL_ID = "PILLID";
	public static final String ARCHIVED = "ARCHIVED";
	public static final String CUSTOM_DESCRIPTION = "CUSTOMDESCRIPTION";
	public static final String CUSTOM_DOSAGE_ID = "CUSTOMDOSAGEID";
	public static final String DOCTOR_COUNT = "DOCTORCOUNT";
	public static final String IMAGE_GUID = "IMAGEGUID";
	public static final String INVISIBLE = "INVISIBLE";
	public static final String LOG_MISSED_DOSES = "LOGMISSEDDOSES";
	public static final String MISSED_DOSES_LAST_CHECKED_TZSECS = "MISSEDDOSESLASTCHECKED_TZSECS";
	public static final String MISSED_DOSES_LAST_CHECKED = "MISSEDDOSESLASTCHECKED";
	public static final String NO_PUSH = "NOPUSH";
	public static final String NOTES = "NOTES";
	public static final String PERSON_ID = "PERSONID";
	public static final String PHARMACY_COUNT = "PHARMACYCOUNT";
	public static final String PRESCRIPTION_NUM = "PRESCRIPTIONNUM";
	public static final String REFILL_ALERT_DOSES = "REFILLALERTDOSES";
	public static final String REFILLS_REMAINING = "REFILLSREMAINING";
	public static final String REMAINING_QUANTITY = "REMAININGQUANTITY";
	public static final String SECONDARY_REMINDERS = "SECONDARYREMINDERS";
	public static final String WEEKDAYS= "WEEKDAYS";
	public static final String LAST_MANAGED_ID_NOTIFIED = "lastManagedIdNotified";
	public static final String LAST_MANAGED_ID_NEEDING_NOTIFY = "lastManagedIdNeedingNotify";
	public static final String MAX_NUM_DAILY_DOSES = "maxNumDailyDoses";
	public static final String LIMIT_TYPE = "limitType";
	public static final String DATABASE_NDC = "databaseNDC";
	public static final String MANAGED_DROPPED = "managedDropped";
	public static final String MANAGED_MEDICATION_ID = "managedMedicationId";
	public static final String MANAGED_DESCRIPTION = "managedDescription";
	public static final String DATABASE_MED_FORM_TYPE = "databaseMedFormType";
	public static final String DELETED = "DELETED";
	public static final String DOSAGE_TYPE = "dosageType";
	public static final String SCHEDULED_FREQUENCY = "scheduledFrequency";
    public static final String SCHEDULEDATECHANGED_TZSECS ="SCHEDULEDATECHANGED_TZSECS";
	public static final String DEFAULT_IMAGE_CHOICE ="defaultImageChoice";
	public static final String DEFAULT_SERVICE_IMAGE_ID ="defaultServiceImageID";
	public static final String NEED_FDB_UPDATE = "needFDBUpdate";
	public static final String SCHEDULE_CHOICE = "scheduleChoice";


	// Pill Schedule
	public static final String PILLTIME= "PILLTIME";


	// Pill History Table

	public static final String HISTORY_EVENT_GUID = "GUID";
	public static final String HISTORY_EVENT_OPID = "OPID";
	public static final String HISTORY_EVENT_CREATIONDATE = "CREATIONDATE";
	public static final String HISTORY_EVENT_DESCRIPTION = "EVENTDESCRIPTION";
	public static final String HISTORY_EVENT_OPERATION = "OPERATION";
	public static final String HISTORY_EVENT_OPERATION_DATA = "OPERATIONDATA";
	public static final String HISTORY_EVENT_PERSON_ID = "PERSONID";
	public static final String HISTORY_EVENT_SCHEDULE_DATE = "SCHEDULEDATE";
	public static final String HISTORY_EVENT_EDIT_TIME = "EDITTIME";
	public static final String HISTORY_EVENT_DELETED = "DELETED";
	public static final String HISTORY_EVENT_CREATE_USERID = "CREATEUSERID";
	public static final String HISTORY_EVENT_UPDATE_USERID = "UPDATEUSERID";
	public static final String HISTORY_EVENT_PILL_NAME = "PILLNAME";
	public static final String HISTORY_EVENT_TZ_SEC = "tz_secs";
	public static final String HISTORY_EVENT_TZ_NAME = "tz_name";
	public static final String HISTORY_EVENT_ADJUSTED_SCHEDULE_DATE = "ADJUSTEDSCHEDULEDATE";


	// History preferences

	public static final String HISTORY_EVENT_MANAGED_DESCRIPTION = "managedDescription";
	public static final String HISTORY_EVENT_CUSTOM_DESCRIPTION = "customDescription";
	public static final String HISTORY_EVENT_DOSAGE_TYPE = "dosageType";
	public static final String IS_POSTPONED_EVENT_ACTIVE ="isPostponedEventActive";
	public static final String FINAL_POSTPONED_DATE_TIME = "finalPostponedDateTime";
	public static final String HISTORY_ACTION_DATE = "actionDate";
	public static final String HISTORY_RECORD_DATE = "recordDate";
	public static final String HISTORY_PREF_SCH_DATE = "scheduleDate";
	public static final String HISTORY_PREF_SCH_FREQUENCY = "scheduleFrequency";
	public static final String HISTORY_PREF_SCH_DAY_PERIOD = "dayPeriod";
	public static final String HISTORY_PREF_WEEKDAYS = "weekdays";
	public static final String HISTORY_PREF_START_DATE = "startDate";
	public static final String HISTORY_PREF_END_DATE = "endDate";
	public static final String HISTORY_PREF_SCH_TYPE = "scheduleChoice";
	public static final String HISTORY_PREF_SCH_GUID = "scheduleGuid";

	// Log Entry Table Columns
	public static final String LOG_ENTRY_DATE_ADDED = "DATEADDED";
	public static final String LOG_ENTRY = "ENTRY";
	public static final String LOG_ENTRY_GUID = "GUID";
	public static final String LOG_ENTRY_LAST_UPLOAD_ATTEMPT = "LASTUPLOADATTEMPT";
	public static final String LOG_ENTRY_LAST_UPLOAD_RESPONSE = "LASTUPLOADRESPONSE";
	public static final String LOG_ENTRY_ACTION = "ACTION";

	//Pending Image Sync Requests Table
	public static final String PENDING_IMAGE_SYNC_REQUESTS_ID = "_id";
	public static final String PENDING_IMAGE_SYNC_REQUESTS_PILL_ID = "PILLID";
	public static final String PENDING_IMAGE_SYNC_REQUESTS_IMAGE_GUID = "IMAGEGUID";
	public static final String PENDING_IMAGE_SYNC_REQUESTS_NEEDS_UPLOAD = "NEEDSUPLOAD";
	public static final String PENDING_IMAGE_SYNC_REQUESTS_NEEDS_DELETE = "NEEDSDELETE";

	//IMAGE_FAILURE_ENTRIES table
	public static final String IMAGE_FAILURE_IMAGE_ID = "IMAGEID";
	public static final String IMAGE_FAILURE_TYPE = "TYPE";

	/** Table Names **/
	public static final String USER_TABLE = "USER";
	public static final String PILL_TABLE = "PILL";
	public static final String PILL_SCHEDULE_TABLE = "PILL_SCHEDULE";
	public static final String PILL_PREFERENCE_TABLE = "PILLPREFERENCE";
	public static final String USER_PREFERENCE_TABLE = "USERPREFERENCE";
	public static final String HISTORY_TABLE = "PILL_HISTORY";
	public static final String LOG_ENTRY_TABLE = "LOG_ENTRY";
	public static final String USER_REMINDERS_TABLE = "USERREMINDERS";
	public static final String PASSED_REMINDERS_TABLE = "PASTREMINDERS";
	public static final String PENDING_IMAGE_SYNC_REQUESTS_TABLE = "PENDINGIMAGESYNCREQUESTS";
	public static final String FDB_IMAGE_TABLE = "FDBIMAGE";
	public static final String CUSTOM_IMAGE_TABLE = "CUSTOMIMAGE";
	public static final String IMAGE_FAILURE_ENTRIES_TABLE = "IMAGE_FAILURE_ENTRIES";
	public static final String HISTORY_PREFERENCE_TABLE = "HISTORY_PREFERENCE";

	// upgrade to 3.8 queries.
	public static final String ALTER_TABLE_RENAME_PILL_PREFERENCES = "ALTER TABLE PILLPREFERENCE RENAME TO TMP_PILLPREFERENCE;";
	public static final String DROP_TABLE_TEMP_PILL_PREFERENCES = "DROP TABLE TMP_PILLPREFERENCE;";

	//Adding schedule choice column in the schema
	public static final String ALTER_TABLE_INSERT_PILL_PREFERENCES_SCHEDULE_CHOICE = "INSERT INTO PILLPREFERENCE (PILLID , ARCHIVED , CUSTOMDESCRIPTION , CUSTOMDOSAGEID , DOCTORCOUNT , IMAGEGUID , INVISIBLE , LOGMISSEDDOSES , MISSEDDOSESLASTCHECKED , NOPUSH , NOTES , PERSONID , PHARMACYCOUNT , PRESCRIPTIONNUM , REFILLALERTDOSES , REFILLSREMAINING , REMAININGQUANTITY , SECONDARYREMINDERS , WEEKDAYS , lastManagedIdNotified , lastManagedIdNeedingNotify , dosageType , maxNumDailyDoses , databaseNDC , managedDropped , managedMedicationId  , managedDescription , databaseMedFormType , DELETED ,limitType , scheduledFrequency , MISSEDDOSESLASTCHECKED_TZSECS , SCHEDULEDATECHANGED_TZSECS , defaultImageChoice , defaultServiceImageID  , needFDBUpdate) " +
			" SELECT PILLID , ARCHIVED , CUSTOMDESCRIPTION , CUSTOMDOSAGEID , DOCTORCOUNT , IMAGEGUID , INVISIBLE , LOGMISSEDDOSES , MISSEDDOSESLASTCHECKED , NOPUSH , NOTES , PERSONID , PHARMACYCOUNT , PRESCRIPTIONNUM , REFILLALERTDOSES , REFILLSREMAINING , REMAININGQUANTITY , SECONDARYREMINDERS , WEEKDAYS , lastManagedIdNotified , lastManagedIdNeedingNotify , dosageType , maxNumDailyDoses , databaseNDC , managedDropped , managedMedicationId  , managedDescription , databaseMedFormType , DELETED ,limitType , scheduledFrequency , MISSEDDOSESLASTCHECKED_TZSECS , SCHEDULEDATECHANGED_TZSECS , defaultImageChoice , defaultServiceImageID  , needFDBUpdate FROM TMP_PILLPREFERENCE;";

	public static final String CREATE_TABLE_TEMP_LATE_REMINDERS = "CREATE TABLE IF NOT EXISTS TEMP_PASTREMINDERS (_id integer primary key, PILLID VARCHAR(300), PILLTIME VARCHAR(300));";
	public static final String DROP_TABLE_TEMP_LATE_REMINDERS = "DROP TABLE IF EXISTS TEMP_PASTREMINDERS";
	public static final String COPY_FROM_LATE_REMINDERS_TO_TEMP_TABLE = "INSERT INTO TEMP_PASTREMINDERS (PILLID, PILLTIME) SELECT PILLID,PILLTIME FROM PASTREMINDERS;";
	public static final String COPY_TO_LATE_REMINDERS_FROM_TEMP_TABLE = "INSERT INTO PASTREMINDERS (PILLID, PILLTIME) SELECT PILLID,PILLTIME FROM TEMP_PASTREMINDERS;";

	//upgrade to 3.9 queries
	public static final String ALTER_TABLE_RENAME_USER = "ALTER TABLE USER RENAME TO TMP_USER;";
	public static final String ALTER_TABLE_INSERT_USER = "INSERT INTO USER (USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES) " +
			" SELECT USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES FROM TMP_USER;";
	public static final String DROP_TABLE_TEMP_USER = "DROP TABLE TMP_USER;";


	public static final String GET_DISPLAYNAME_QUERY = "SELECT * from USER where USERID=?;";

	public static final String GET_PRIMARY_USERID_QUERY_ENABLED = "SELECT * from USER where USERTYPE='primary' AND ENABLED = 'Y';";

	public static final String GET_PROXY_USERS_BY_USERID_QUERY = "SELECT * from USER where USERTYPE=? AND ENABLED='Y' order by FIRSTNAME;";

	public static final String GET_DRUG_BY_PILL_ID_QUERY = "Select P.PILLID, P.USERID, P.PILLNAME, P.CREATED, P.DAYPERIOD, P.DOSE, P.NUMPILLS, P.INSTRUCTION, P.HASUNDO, P.LAST_TAKEN, P.EFFLASTTAKEN, P.NOTIFYAFTER, P.NEXT, P.OVERDUE, P.START, P.END, P.TAKEPILLAFTER, P.SKIPPILLAFTER, P.MAXPOSTPONETIME, P.SERVEREDITTIME, P.SERVEREDITGUID, P.INSTRUCTIONS, P.SCHEDULE_GUID, PP.ARCHIVED, PP.CUSTOMDESCRIPTION, PP.CUSTOMDOSAGEID, PP.DOCTORCOUNT, PP.IMAGEGUID, PP.INVISIBLE, PP.LOGMISSEDDOSES, PP.MISSEDDOSESLASTCHECKED, PP.NOPUSH, PP.NOTES, PP.PERSONID, PP.PHARMACYCOUNT, PP.PRESCRIPTIONNUM, PP.REFILLALERTDOSES, PP.REFILLSREMAINING , PP.REMAININGQUANTITY, PP.SECONDARYREMINDERS, PP.WEEKDAYS, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, " +
			"PP.maxNumDailyDoses, PP.limitType, PP.databaseNDC, PP.managedDropped, PP.managedMedicationId, PP.managedDescription, PP.databaseMedFormType, PP.deleted, PP.dosageType, PP.scheduledFrequency, PP.defaultImageChoice, PP.defaultServiceImageID, PP.needFDBUpdate, U.FIRSTNAME, PP.scheduleChoice, P.SCHEDULE_GUID from Pill P, PILLPREFERENCE PP, USER U where P.PILLID=? AND P.PILLID = PP.PILLID AND P.USERID = U.USERID;";

	public static final String GET_DRUG_DOSE_BY_PILL_ID_QUERY = "Select PP.CUSTOMDESCRIPTION, PP.managedDescription from Pill P, PILLPREFERENCE PP where P.PILLID=? AND P.PILLID = PP.PILLID";

	public static final String GET_DRUG_LIST_QUERY = "Select P.PILLID, P.USERID, P.PILLNAME, P.CREATED, P.DAYPERIOD, P.DOSE, P.NUMPILLS, P.INSTRUCTION, P.HASUNDO, P.LAST_TAKEN, P.EFFLASTTAKEN, P.NEXT, P.OVERDUE, P.START, P.END, P.TAKEPILLAFTER, P.SKIPPILLAFTER, P.MAXPOSTPONETIME, P.SERVEREDITTIME, P.SERVEREDITGUID, P.INSTRUCTIONS, P.SCHEDULE_GUID, PP.ARCHIVED, PP.customDescription, PP.CUSTOMDOSAGEID, PP.DOCTORCOUNT, PP.IMAGEGUID, PP.INVISIBLE, PP.LOGMISSEDDOSES, PP.MISSEDDOSESLASTCHECKED, PP.NOPUSH, PP.NOTES, PP.PERSONID, PP.PHARMACYCOUNT, PP.PRESCRIPTIONNUM, PP.REFILLALERTDOSES, PP.REFILLSREMAINING , PP.REMAININGQUANTITY, PP.SECONDARYREMINDERS, PP.WEEKDAYS, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, " +
			"PP.maxNumDailyDoses, PP.limitType, PP.databaseNDC, PP.managedDropped, PP.managedMedicationId, PP.managedDescription, PP.databaseMedFormType, PP.defaultImageChoice, PP.defaultServiceImageID, PP.needFDBUpdate, PP.deleted, PP.dosageType, U.USERID, P.NOTIFYAFTER, UR.REMINDERS, PP.scheduleChoice, PP.scheduledFrequency, P.SCHEDULE_GUID " +
			"from Pill P, PILLPREFERENCE PP, USER U, USERREMINDERS UR where U.USERID = P.USERID " +
			"AND P.PILLID = PP.PILLID AND U.USERID = UR.USERID AND U.ENABLED = 'Y' " +
			"AND PP.ARCHIVED != '1' AND PP.INVISIBLE != '1' AND ( PP.managedDropped = 'null' OR PP.managedDropped IS NULL OR PP.managedDropped != '1') AND (PP.DELETED = 'null' OR PP.DELETED IS NULL OR PP.DELETED != '1');";


	public static final String GET_ALL_DRUGS_SCHEDULE_MAIN_SCREEN_QUERY = "Select P.PILLID, P.USERID, P.PILLNAME, P.DAYPERIOD, P.DOSE, P.LAST_TAKEN, P.EFFLASTTAKEN, P.NOTIFYAFTER, P.START, P.END, PP.IMAGEGUID, PP.ARCHIVED, PP.INVISIBLE, PP.WEEKDAYS, PP.DATABASEMEDFORMTYPE, PP.DELETED, PP.DOSAGETYPE, S.PILLTIME, U.USERTYPE, U.ENABLED, U.FIRSTNAME, UP.EARLYDOSEWARNING, PP.managedDescription, PP.customDescription, PP.scheduledFrequency"
			+ " FROM PILL P, PILLPREFERENCE PP, PILL_SCHEDULE S, USER U, USERPREFERENCE UP WHERE P.PILLID = PP.PILLID AND P.PILLID = S.PILLID AND P.USERID = U.USERID AND P.USERID = UP.USERID AND (PP.ARCHIVED = '0' OR PP.ARCHIVED IS NULL OR PP.ARCHIVED = '') AND (PP.DELETED = '0' OR PP.DELETED IS NULL OR PP.DELETED = '') AND (PP.INVISIBLE = '0' OR PP.INVISIBLE IS NULL OR PP.INVISIBLE = '') AND (PP.WEEKDAYS IS NULL OR PP.WEEKDAYS = '' OR PP.WEEKDAYS LIKE ?) AND P.DAYPERIOD IS NOT NULL AND P.DAYPERIOD != '' AND S.PILLTIME IS NOT NULL AND S.PILLTIME != '' AND PP.scheduleChoice = 'scheduled' AND DATETIME(P.START) <= DATETIME(?) AND (DATETIME(P.END) >= DATETIME(?) OR P.END = '-1') AND U.ENABLED='Y'"
			+ "  AND ((PP.dosageType!='managed' AND PP.INVISIBLE = '0') OR PP.managedDropped != '1') ORDER BY S.PILLTIME, U.USERTYPE, U.FIRSTNAME COLLATE NOCASE ASC, P.PILLNAME COLLATE NOCASE ASC;";	//Placeholders 0-weekdays, 1-weekdays, 2-end

public static  final  String GET_FUTIRE_DRUGS_FOR_CALENDAR_QUERY = "Select *"
		+ " FROM PILL P, PILLPREFERENCE PP, PILL_SCHEDULE S, USER U, USERPREFERENCE UP WHERE P.PILLID = PP.PILLID AND P.PILLID = S.PILLID AND P.USERID = U.USERID AND P.USERID = UP.USERID AND (PP.ARCHIVED = '0' OR PP.ARCHIVED IS NULL OR PP.ARCHIVED = '') AND (PP.DELETED = '0' OR PP.DELETED IS NULL OR PP.DELETED = '') AND (PP.INVISIBLE = '0' OR PP.INVISIBLE IS NULL OR PP.INVISIBLE = '') AND (PP.WEEKDAYS IS NULL OR PP.WEEKDAYS = '' OR PP.WEEKDAYS LIKE ?) AND P.DAYPERIOD IS NOT NULL AND P.DAYPERIOD != '' AND S.PILLTIME IS NOT NULL AND S.PILLTIME != '' AND PP.scheduleChoice = 'scheduled' AND DATETIME(P.START) <= DATETIME(?) AND (DATETIME(P.END) >= DATETIME(?) OR P.END = '-1') AND U.ENABLED='Y'"
		+ "  AND ((PP.dosageType!='managed' AND PP.INVISIBLE = '0') OR PP.managedDropped != '1') ORDER BY S.PILLTIME, U.USERTYPE, U.FIRSTNAME COLLATE NOCASE ASC, P.PILLNAME COLLATE NOCASE ASC;";

	public static final String GET_HISTORY_EVENTS_SCHEDULE_SCREEN_QUERY = "SELECT P.PILLID, P.PILLNAME, P.NOTIFYAFTER, P.USERID, PP.IMAGEGUID, PP.DOSAGETYPE, PP.managedDescription, PP.customDescription, PP.scheduleChoice, U.FIRSTNAME, U.USERTYPE, H.SCHEDULEDATE, H.tz_secs, H.OPERATION  from " + HISTORY_TABLE + " H," + PILL_TABLE + " P, "+ PILL_PREFERENCE_TABLE + " PP, " + USER_TABLE + " U WHERE " + "H.PILLID = P.PILLID AND P.USERID = U.USERID AND H.PILLID = PP.PILLID AND PP.DELETED != 1 AND PP.ARCHIVED = '0' AND (DATETIME(H.SCHEDULEDATE)>= DATETIME(?) AND DATETIME(H.SCHEDULEDATE) < DATETIME(?)) AND PP.scheduleChoice = 'scheduled' AND ((PP.dosageType!='managed' AND PP.INVISIBLE = '0') OR (PP.dosageType = 'managed' AND PP.managedDropped != '1')) ORDER BY H.SCHEDULEDATE ASC, U.USERTYPE COLLATE NOCASE ASC, U.FIRSTNAME COLLATE NOCASE ASC;";

	public static final String GET_LOG_ENTRY = "SELECT ENTRY FROM LOG_ENTRY;";

	public static final String GET_SCHEDULES_BY_PILL_ID_QUERY = "SELECT PILLTIME FROM PILL_SCHEDULE where PILLID=? AND PILLTIME IS NOT NULL;";

	public static final String GET_SORTED_ARCHIVED_DRUG_LIST_QUERY = "Select P.PILLID, P.USERID, P.PILLNAME, P.DOSE,PP.IMAGEGUID, PP.ARCHIVED, PP.INVISIBLE, PP.DELETED, PP.dosageType, PP.managedDescription, PP.customDescription, PP.NOTES, U.USERTYPE, U.ENABLED, U.FIRSTNAME " +
			"FROM PILL P, PILLPREFERENCE PP, USER U WHERE P.PILLID = PP.PILLID AND PP.ARCHIVED = '1' AND PP.DELETED = '0' AND ((PP.dosageType!='managed' AND PP.INVISIBLE = '0') OR (PP.dosageType = 'managed' AND PP.managedDropped != '1')) AND P.USERID = U.USERID ORDER BY U.USERTYPE COLLATE NOCASE ASC, U.FIRSTNAME COLLATE NOCASE ASC, (CASE WHEN PP.dosageType = 'managed' THEN 1 ELSE 0 END) ASC, P.PILLNAME COLLATE NOCASE ASC;";

	public static final String GET_USER_LIST_FOR_ARCHIVE_SCREEN_QUERY = "Select userId, firstname, enabled, userType from user where enabled = 'Y' or enabled = 'y' ORDER BY userType collate nocase asc, firstname collate nocase asc;";

	public static final String GET_ARCHIVED_DRUG_DETAILS_QUERY = "Select P.PILLID, P.PILLNAME, P.DAYPERIOD, P.START, PP.managedDescription,PP.IMAGEGUID, PP.CUSTOMDESCRIPTION, PP.notes, P.instruction, PP.PRESCRIPTIONNUM, PP.dosageType, PP.weekdays, PP.scheduledFrequency, U.FIRSTNAME " +
			"FROM PILL P, PILLPREFERENCE PP, USER U WHERE P.PILLID = ? AND P.PILLID = PP.PILLID AND P.USERID = U.USERID;";

	public static final String QUICKVIEW_FLAG_CHECK_QUERY = "SELECT QUICKVIEWOPTINED FROM USERPREFERENCE where USERID=?;";

	public static final String GET_DRUG_LIST_BY_USER_ID_QUERY_WITHOUT_SCHEDULE_NEW = "Select P.PILLID, P.USERID, P.PILLNAME, P.DOSE, P.START, P.END, P.DAYPERIOD, PP.ARCHIVED, PP.CUSTOMDESCRIPTION, PP.IMAGEGUID, PP.INVISIBLE, PP.WEEKDAYS, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, " +
			"PP.limitType, PP.managedDropped, PP.managedDescription, PP.DELETED, PP.dosageType, PP.NOTES, PP.maxNumDailyDoses, U.FIRSTNAME, PP.scheduleChoice, P.SCHEDULE_GUID from Pill P, PILLPREFERENCE PP, USER U where P.USERID=? AND P.PILLID = PP.PILLID AND P.USERID = U.USERID AND PP.ARCHIVED = '0' AND PP.DELETED = '0' AND (PP.INVISIBLE != '1' OR PP.managedDropped != '1');";

	public static final String GET_SCHEDULE_COUNT_BY_PILL_ID_QUERY = "SELECT COUNT('PILLTIME') FROM PILL_SCHEDULE where PILLID=? AND PILLTIME IS NOT NULL;";

	public static final String GET_SCHEDULE_DATE_BY_PILLID_FROM_HISTORY_QUERY = "SELECT SCHEDULEDATE FROM PILL_HISTORY where PILLID=?;";

    public static final String GET_SCHEDULE_DATE_FROM_HISTORY_QUERY = "SELECT SCHEDULEDATE FROM PILL_HISTORY ORDER BY SCHEDULEDATE DESC LIMIT 1;";

	public static final String GET_EVENT_DESCRIPTION_BY_PILLID_FROM_HISTORY_QUERY = "SELECT EVENTDESCRIPTION FROM PILL_HISTORY where PILLID=?;";

	public static final String GET_USERS_QUERY = "SELECT DISTINCT USERID,USERTYPE,RELATIONDESC,RELID,NICKNAME,DISPLAYNAME,FIRSTNAME,LASTNAME,MIDDLENAME,ENABLED,LASTSYNCTOKEN,MRN,GENDER from USER where ENABLED='Y' ORDER BY USERTYPE, " + FIRST_NAME;

	public static final String GET_MEMBERS_QUERY = "SELECT DISTINCT USERID,USERTYPE,RELATIONDESC,RELID,NICKNAME,DISPLAYNAME,FIRSTNAME,LASTNAME,MIDDLENAME,ENABLED,LASTSYNCTOKEN,MRN,GENDER from USER ORDER BY USERTYPE," + FIRST_NAME;

	public static final String GET_HISTORY_EVENT_COUNT = "SELECT COUNT('SCHEDULEDATE') FROM PILL_HISTORY where PILLID=? AND SCHEDULEDATE=? AND OPERATION != 'EMPTY';";

	public static final String GET_HISTORY_EVENT_EMPTY_COUNT = "SELECT COUNT('SCHEDULEDATE') FROM PILL_HISTORY where PILLID=? AND SCHEDULEDATE=? AND OPERATION = 'EMPTY'";

	//CAST(strftime('%s', date_field)  AS  integer) <=CAST(strftime('%s', '2015-01-01')  AS  integer) ;

	public static final String GET_HISTORY_EVENTS = "SELECT H.PILLID, H.PILLNAME, H.CUSTOMDESCRIPTION, H.tz_secs, H.tz_name, H.dosageType, H.managedDescription, H.OPID, H.DELETED, H.GUID, H.UPDATEUSERID, H.CREATIONDATE, H.OPERATION, H.EVENTDESCRIPTION, H.SCHEDULEDATE, H.EDITTIME, H.PERSONID, H.OPERATIONDATA, H.CREATEUSERID, HP.startDate, HP.endDate, HP.scheduleFrequency, HP.dayPeriod, HP.weekdays, HP.scheduleChoice, HP.isPostponedEventActive, HP.finalPostponedDateTime, HP.actionDate, HP.recordDate, HP.scheduleGuid FROM PILL_HISTORY H JOIN HISTORY_PREFERENCE HP  WHERE H.GUID = HP.GUID AND H.PERSONID = ? ORDER BY DATETIME(H.SCHEDULEDATE) DESC, PILLNAME COLLATE NOCASE ASC;";

	public static final String GET_HISTORY_DOSE_DAYS_SETTING = "SELECT " + DOSE_HISTORY_DAYS + " from " + USER_PREFERENCE_TABLE + " WHERE " + USER_ID + "= ?";

	public static final String GET_HISTORY_OPERATION_FOR_NOTIFY_AFTER = "SELECT PILLID, OPERATION, CREATIONDATE FROM " +  HISTORY_TABLE + " WHERE PILLID = ? AND OPERATION != 'EMPTY' ORDER BY CREATIONDATE DESC LIMIT 1;";

	public static final String GET_HISTORY_EVENT_COUNT_FOR_TODAY = "select H.PILLID from " + HISTORY_TABLE + " H where H.PILLID=? AND (DATE(CREATIONDATE,'unixepoch') = DATE('now')) AND H.OPERATION = '" + PillpopperConstants.ACTION_TAKE_PILL_HISTORY + "'";

	public static final String GET_USER_PREFERENCES = "SELECT * from " + USER_PREFERENCE_TABLE + " WHERE " + USER_ID + "= ?";


	public static final String GET_HISTORY_EDIT_SCREEN_DRUG_QUERY = "SELECT H.pillId, H.personId, H.pillName, H.dosageType, H.managedDescription, H.customDescription, H.guid, H.scheduleDate, H.CREATIONDATE, H.editTime, H.operation, H.OPID, H.eventDescription, H.tz_secs" +
			" FROM PILL_HISTORY H WHERE H.guid = ? LIMIT 1;";

	public static final String GET_USERS_DATA = "SELECT * from USER U,USERREMINDERS UR WHERE U.USERID = UR.USERID ORDER BY USERTYPE, " + FIRST_NAME;

	public static final String GET_SECONDARY_REMINDERS_DATA = "SELECT SECONDARYREMINDERPERIODSECS from USERPREFERENCE WHERE  " + USER_ID + "= ?";

	public static final String GET_PRIMARY_USERID_QUERY = "SELECT * from USER where USERTYPE='primary'";

	public static final String GET_DISCONTINUED_MEDICATIONS = "SELECT P.pillId, P.pillName, PP.managedDescription, U.FIRSTNAME, U.USERID FROM PILL P, PILLPREFERENCE PP, USER U WHERE P.pillId = PP.pillId AND P.userId = U.userId AND PP.managedDropped = '1' AND PP.invisible = '0' AND U.ENABLED = 'Y' ORDER BY U.userType, U.USERID, U.firstName collate nocase asc, P.pillName collate nocase asc;";


	public static final String GET_ALL_DRUGS_FOR_KPHC = "Select P.PILLID, P.USERID, P.PILLNAME, P.DOSE, PP.ARCHIVED, PP.CUSTOMDESCRIPTION, " +
			"PP.IMAGEGUID, PP.INVISIBLE, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, " +
			"PP.managedDropped, PP.managedDescription, PP.DELETED, PP.dosageType, PP.WEEKDAYS, PP.limitType, PP.notes, PP.maxNumDailyDoses, PP.scheduleChoice " +
			"from Pill P, PILLPREFERENCE PP where P.PILLID=PP.PILLID AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.ARCHIVED = '0';";

	public static final String GET_ALL_INTERVAL_DRUGS = "Select * from Pill P, PILLPREFERENCE PP, PILL_SCHEDULE PS where P.PILLID = PP.PILLID AND P.PILLID = PS.PILLID AND PP.INVISIBLE !='1' AND PP.DELETED !='1' AND PP.scheduleChoice != 'scheduled' AND P.INTERVAL != '0' ";
	public static final String GET_CREATION_DATE_BY_PILLID_FROM_HISTORY_QUERY = "SELECT CREATIONDATE FROM PILL_HISTORY where PILLID=? AND OPERATION != 'EMPTY' ORDER BY CREATIONDATE DESC;";

	public static final String GET_ENABLED_USERS_MEDICATION_COUNT = "Select count(*) as count from Pill P, PILLPREFERENCE PP where P.USERID in (select USERID from USER where ENABLED = 'Y')  AND P.PILLID = PP.PILLID AND PP.ARCHIVED = '0' AND PP.DELETED = '0' AND (PP.INVISIBLE != '1' OR PP.managedDropped != '1')";

	public static final String GET_REMINDERSOUND_PATH="select REMINDERSOUNDFILENAME from USERPREFERENCE where USERID = ?";

	public static final String CHECK_USER_REMINDERS_PREF = "select * from " + USER_REMINDERS_TABLE + " where " + USER_ID + "=?";

	public static final String GET_MEDICATIONS_FOR_SCHEDULE = "Select P.PILLID, P.USERID, P.PILLNAME, P.CREATED, P.DAYPERIOD, P.DOSE, P.NUMPILLS, P.INSTRUCTION, P.HASUNDO, P.LAST_TAKEN," +
			" P.EFFLASTTAKEN, P.NEXT, P.OVERDUE, P.START, P.END, P.TAKEPILLAFTER, P.SKIPPILLAFTER, P.MAXPOSTPONETIME, P.SERVEREDITTIME, P.SERVEREDITGUID, P.INSTRUCTIONS, PP.ARCHIVED, PP.CUSTOMDESCRIPTION," +
			" PP.CUSTOMDOSAGEID, PP.DOCTORCOUNT, PP.IMAGEGUID, PP.INVISIBLE, PP.LOGMISSEDDOSES, PP.MISSEDDOSESLASTCHECKED, PP.NOPUSH, PP.NOTES, PP.PERSONID, PP.PHARMACYCOUNT, PP.PRESCRIPTIONNUM, " +
			"PP.REFILLALERTDOSES, PP.REFILLSREMAINING , PP.REMAININGQUANTITY, PP.SECONDARYREMINDERS, PP.WEEKDAYS, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, PP.maxNumDailyDoses, PP.limitType, " +
			"PP.databaseNDC, PP.managedDropped, PP.managedMedicationId, PP.managedDescription, PP.databaseMedFormType, PP.deleted, PP.dosageType, PP.defaultImageChoice, PP.defaultServiceImageID, PP.needFDBUpdate, PP.scheduleChoice, PP.scheduledFrequency from Pill P, PILLPREFERENCE PP, USER U " +
			"where U.USERID=P.USERID AND U.ENABLED = 'Y' AND P.USERID=? AND P.PILLID = PP.PILLID AND PP.ARCHIVED = '0' AND PP.DELETED = '0' AND (PP.INVISIBLE != '1' OR PP.managedDropped != '1') ORDER BY P.PILLNAME COLLATE NOCASE ASC;";


	public static final String CHECK_HISTORY_EVENT_COUNT_FOR_SCH_TIME = "select count(ph.PILLID) as EventCount from PILL_HISTORY ph where ph.SCHEDULEDATE = '%s' and ph.PILLID = '%s' AND ph.OPERATION != 'EMPTY'";

	public static final String GET_PILLID_FROM_LATE_REMINDERS = "select DISTINCT PILLID from PASTREMINDERS;";

	public static final String GET_PAST_REMINDERS_QUERY = "Select P.PILLID, P.USERID, P.PILLNAME, P.CREATED, P.DAYPERIOD, P.DOSE, P.NUMPILLS, P.INSTRUCTION, P.HASUNDO, P.LAST_TAKEN, P.EFFLASTTAKEN, P.NEXT, P.OVERDUE, P.START, P.END, P.TAKEPILLAFTER, P.SKIPPILLAFTER, P.MAXPOSTPONETIME, P.SERVEREDITTIME, P.SERVEREDITGUID, P.INSTRUCTIONS, PP.ARCHIVED, PP.customDescription, PP.CUSTOMDOSAGEID, PP.DOCTORCOUNT, PP.IMAGEGUID, PP.INVISIBLE, PP.LOGMISSEDDOSES, PP.MISSEDDOSESLASTCHECKED, PP.NOPUSH, PP.NOTES, PP.PERSONID, PP.PHARMACYCOUNT, PP.PRESCRIPTIONNUM, PP.REFILLALERTDOSES, PP.REFILLSREMAINING , PP.REMAININGQUANTITY, PP.SECONDARYREMINDERS, PP.WEEKDAYS, PP.lastManagedIdNotified, PP.lastManagedIdNeedingNotify, " +
			"PP.maxNumDailyDoses, PP.limitType, PP.databaseNDC, PP.managedDropped, PP.managedMedicationId, PP.managedDescription, PP.databaseMedFormType, PP.defaultImageChoice, PP.defaultServiceImageID, PP.needFDBUpdate, PP.deleted, PP.dosageType, U.USERID, P.NOTIFYAFTER, PP.scheduleChoice, PP.scheduledFrequency, P.SCHEDULE_GUID " +
			"from Pill P, PILLPREFERENCE PP, USER U, USERREMINDERS UR where U.USERID = P.USERID " +
			"AND P.PILLID = PP.PILLID AND U.USERID = UR.USERID AND U.ENABLED = 'Y' AND UR.REMINDERS = 'Y' " +
			"AND PP.ARCHIVED != '1' AND PP.INVISIBLE != '1' AND PP.scheduleChoice = 'scheduled' AND P.PILLID = ? AND ( PP.managedDropped = 'null' OR PP.managedDropped IS NULL OR PP.managedDropped != '1') AND (PP.DELETED = 'null' OR PP.DELETED IS NULL OR PP.DELETED != '1');";


	public static final String GET_NOTIFY_AFTER_VALUE_BY_PILL_ID_QUERY = "SELECT PILLID, NOTIFYAFTER FROM " + PILL_TABLE + " where PILLID = ?;";

	public static final String GET_PAST_REMINDERS_ENTRIES = "SELECT PILLID, PILLTIME FROM PASTREMINDERS;";

	public static final String DELETE_REMINDERS = "DELETE FROM PILL_SCHEDULE where PILLID=?";

	public static final String GET_HISTORY_EVENT_COUNT_FOR_OP_ID = "SELECT OPID FROM PILL_HISTORY ORDER BY OPID+0 DESC LIMIT 1;";

	public static final String GET_IMAGE_GUID_BY_PILL_ID_QUERY = "SELECT P.PILLID, PP.IMAGEGUID FROM PILL P, PILLPREFERENCE PP WHERE P.PILLID = PP.PILLID AND P.PILLID = ?";

	public static final String GET_ALL_PENDING_IMAGE_SYNC_REQUESTS_QUERY = "SELECT * FROM PendingImageSyncRequests";

	public static final String GET_FIRST_PENDING_IMAGE_REQUEST_ON_SUCCESS = "SELECT * FROM PendingImageSyncRequests WHERE PillId = ? AND ImageGuid = ? AND needsUpload = ? AND needsDelete = ?";

	public static final String GET_USER_LAST_SYNC_TOKEN = "SELECT " + LAST_SYNC_TOKEN + " from USER where USERID=?;";

	public static final String GET_ALL_USER_IDS_QUERY = "SELECT DISTINCT USERID from USER;";

	public static final String GET_NOTES_QUERY = "SELECT NOTES from PILLPREFERENCE where PILLID=?;";

	public static final String GET_PILL_IDS_BY_USERID = "Select P.PILLID from Pill P where P.USERID=?;";

	public static final String GET_USER_TIME_ZONE = "SELECT U." + USER_ID + ", U." + USER_TYPE + ", UP." + TZ_NAME + ", UP." + TZ_SECS + " FROM USERPREFERENCE UP, USER U WHERE U.USERID = UP.USERID AND U.USERTYPE='primary'";

	public static final String GET_CREATION_TIME_ZONE_BY_PILLID_FROM_HISTORY_QUERY = "SELECT "+HISTORY_EVENT_TZ_SEC+","+HISTORY_EVENT_TZ_NAME+" FROM PILL_HISTORY where PILLID=? AND OPERATION != 'EMPTY' ORDER BY CREATIONDATE DESC;";

    public static final String GET_TZSECS_BY_PILL_ID_QUERY = "SELECT P."+LAST_TAKEN_TZSECS+",P."+EFF_LAST_TAKEN_TZSECS+",P."+NOTIFY_AFTER_TZSECS+", PP."+MISSED_DOSES_LAST_CHECKED_TZSECS+" FROM PILL P, PILLPREFERENCE PP WHERE P.PILLID = PP.PILLID AND P.PILLID = ?";

	public static final String GET_ALL_NEW_KPHC_DRUGS = "Select distinct P.USERID,U.FIRSTNAME "+
			"from Pill P, PILLPREFERENCE PP, USER U  where P.PILLID=PP.PILLID AND P.USERID = U.USERID AND U.ENABLED='Y' AND (( PP.lastManagedIdNotified is null AND PP.lastManagedIdNeedingNotify not null) OR (PP.lastManagedIdNotified ='' AND PP.lastManagedIdNeedingNotify !='')) AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.managedDropped != '1' AND PP.ARCHIVED = '0' ORDER BY U.USERTYPE, U." + FIRST_NAME;

	public static final String GET_ALL_UPDATED_KPHC_DRUGS = "Select distinct P.USERID,U.FIRSTNAME "+
			"from Pill P, PILLPREFERENCE PP , USER U  where P.PILLID=PP.PILLID AND P.USERID = U.USERID AND U.ENABLED='Y' AND (PP.lastManagedIdNotified !='' AND PP.lastManagedIdNeedingNotify !='' AND PP.lastManagedIdNotified !=PP.lastManagedIdNeedingNotify) AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.managedDropped != '1' AND PP.ARCHIVED = '0' ORDER BY USERTYPE, " + FIRST_NAME;

	public static final String GET_ALL_NEW_KPHC_DRUGS_DETAILS = "Select P.PILLID,P.PILLNAME, U.USERID,U.FIRSTNAME, PP.PRESCRIPTIONNUM, P.INSTRUCTION, PP.managedDescription "+
			"from Pill P, PILLPREFERENCE PP, USER U  where P.PILLID=PP.PILLID AND P.USERID = U.USERID AND U.ENABLED='Y' AND (( PP.lastManagedIdNotified is null AND PP.lastManagedIdNeedingNotify not null) OR (PP.lastManagedIdNotified ='' AND PP.lastManagedIdNeedingNotify !='')) AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.managedDropped != '1' AND PP.ARCHIVED = '0' AND U.USERID=? ORDER BY P.PILLNAME COLLATE NOCASE ASC";

	public static final String GET_ALL_UPDATED_KPHC_DRUGS_DETAILS = "Select P.PILLID,P.PILLNAME, U.USERID,U.FIRSTNAME, PP.PRESCRIPTIONNUM, P.INSTRUCTION, PP.managedDescription  "+
			"from Pill P, PILLPREFERENCE PP , USER U  where P.PILLID=PP.PILLID AND P.USERID = U.USERID AND U.ENABLED='Y' AND (PP.lastManagedIdNotified !='' AND PP.lastManagedIdNeedingNotify !='' AND PP.lastManagedIdNotified !=PP.lastManagedIdNeedingNotify) AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.managedDropped != '1' AND PP.ARCHIVED = '0' AND U.USERID=? ORDER BY P.PILLNAME COLLATE NOCASE ASC";

	public static final String UPDATE_KPHC_DRUG_DETAILS_BY_USER = "update PILLPREFERENCE set lastManagedIdNotified = (select lastManagedIdNeedingNotify from PILLPREFERENCE where PILLID ='%s') where PILLID ='%s'";

	public static final String USER_ENABLED_CHECK_QUERY = "SELECT * from USER U, USERREMINDERS UR where U.USERID=? AND U.USERID = UR.USERID AND U.ENABLED = 'Y' AND UR.REMINDERS = 'Y';";

    public static final String ACTIVE_DRUG_CHECK_QUERY = "SELECT COUNT(PP.PILLID) as EventCount from PILLPREFERENCE PP where PP.invisible != '1' AND PP.ARCHIVED = '0' AND PP.PILLID=?;";

	public static final String GET_PAST_REMINDERS_ENTRIES_FOR_TIME = "SELECT PILLID , PILLTIME FROM PASTREMINDERS WHERE PILLTIME=?;";

	public static final String GET_PILL_NAME_BY_PILL_ID = "SELECT P.PILLNAME from PILL P where P.PILLID=?;";

	public static final String CHECK_FOR_UPDATED_ENTRY_QUERY = "SELECT * FROM PASTREMINDERS ORDER BY PILLTIME DESC LIMIT 1;";

	public static final String CHECK_FOR_LATE_REMINDER_ENTRY_QUERY = "SELECT * FROM PASTREMINDERS WHERE PILLID=? AND PILLTIME=?;";

	public static final String CHECK_MED_FOR_MANAGE_DROPPED_QUERY = "SELECT P.PILLID, PP.PILLID, PP.DOSAGETYPE, PP.managedDropped from PILL P, PILLPREFERENCE PP where P.PILLID=? AND P.PILLID = PP.PILLID;";

	public static final String GET_ALL_KPHC_DRUGS_TO_FETCH_FDB_IMAGES = "Select P.PILLID, PP.databaseNDC, PP.defaultServiceImageID, PP.needFDBUpdate, PP.defaultImageChoice, PP.IMAGEGUID " +
			"from Pill P, PILLPREFERENCE PP , USER U  where P.PILLID=PP.PILLID AND P.USERID = U.USERID AND U.ENABLED='Y' AND PP.dosageType='managed' AND PP.invisible != '1' AND PP.managedDropped != '1' ORDER BY PP.ARCHIVED, P.PILLNAME COLLATE NOCASE ASC;";

	public static final String GET_MISSED_DOSE_LAST_CHECKED_QUERY = "select PP.PILLID, PP.MISSEDDOSESLASTCHECKED from PILLPREFERENCE PP where PP.PILLID=?;";

	public static final String GET_IMAGE_DATA_BY_PILL_ID = "SELECT * from FDBIMAGE where PILLID=?";

	public static final String GET_CUSTOM_IMAGE_DATA_BY_IMAGE_ID = "SELECT * from CUSTOMIMAGE where imageID=?";

	public static final String CHECK_FOR_FDB_IMAGE = "SELECT * FROM FDBIMAGE WHERE PILLID = ?";

	public static final String CHECK_FOR_CUSTOM_IMAGE = "SELECT * FROM CUSTOMIMAGE WHERE imageID = ?";

	public static final String CHECK_FOR_LATE_REMINDER_ENTRY_BY_PILLID_QUERY = "SELECT * FROM PASTREMINDERS WHERE PILLID=?;";

    public static final String GET_PILL_ID_FROM_PILL_TABLE = "SELECT P.PILLID FROM PILL P where P.PILLID=?;";

	public static final String GET_FAILED_IMAGE_ENTRIES = "SELECT * FROM IMAGE_FAILURE_ENTRIES;";

	public static final String GET_ENTRY_FROM_RETRY_TABLE_BY_PILLID_IMAGEID = "SELECT R.PILLID, R.IMAGEID, R.TYPE FROM IMAGE_FAILURE_ENTRIES R WHERE R.PILLID=? AND R.IMAGEID=?";
	public static final String GET_DOSAGE_BY_PILLID_QUERY = "SELECT PP.dosageType FROM PILLPREFERENCE PP where PP.PILLID=?";

	public static final String GET_CREATION_DATE_BY_PILLID_AND_SCHEDULE_DATE_FROM_HISTORY_QUERY = "SELECT H.CREATIONDATE FROM PILL_HISTORY H where H.PILLID=? AND H.SCHEDULEDATE = ? AND H.OPERATION != 'EMPTY';";

	public static final String GET_ALL_REMINDERS_ENABLED_USERS = "SELECT * FROM USERREMINDERS WHERE REMINDERS = 'Y';";

	public static final String GET_ALL_PILL_IDS_BY_USER = "Select P.PILLID, P.USERID, PP.ARCHIVED, PP.INVISIBLE, PP.dosageType, PP.DELETED, PP.managedDropped FROM PILL P, PILLPREFERENCE PP WHERE P.USERID=? AND P.PILLID = PP.PILLID AND (PP.ARCHIVED = '0' OR PP.ARCHIVED IS NULL OR PP.ARCHIVED = '') AND (PP.DELETED = '0' OR PP.DELETED IS NULL OR PP.DELETED = '') AND (PP.INVISIBLE = '0' OR PP.INVISIBLE IS NULL OR PP.INVISIBLE = '') AND ((PP.dosageType!='managed' AND PP.INVISIBLE = '0') OR PP.managedDropped != '1');";

	public static final String GET_USER_GENDER = "select U.GENDER from User U where U.USERTYPE = 'primary'";

	public static final String GET_USER_AGE ="select U.AGE from User U where U.USERTYPE ='primary'";

	public static final String ALTER_TABLE_INSERT_USER_FOR_V43 = "INSERT INTO USER (USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER) " +
			" SELECT USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER FROM TMP_USER;";

	public static final String ALTER_TABLE_INSERT_USER_FOR_ISTEEN = "INSERT INTO USER (USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER, AGE) " +
			" SELECT USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER, AGE FROM TMP_USER;";

	public static final String ALTER_TABLE_INSERT_USER_FOR_ISTEENTOGGLEENABLED = "INSERT INTO USER (USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER, AGE, ISTEEN) " +
			" SELECT USERID, USERTYPE, RELATIONDESC, RELID, ENABLED, NICKNAME, DISPLAYNAME, FIRSTNAME, LASTNAME , MIDDLENAME , LASTSYNCTOKEN , HASCHANGES, GENDER, AGE, ISTEEN FROM TMP_USER;";

	public static final String GET_HISTORY_PREFERENCES = "SELECT * from HISTORY_PREFERENCE HP where HP.GUID=?";

	public static final String GET_RECENT_POSTPONE_HISTORY_EVENT_FOR_PILLID = "SELECT H.PILLID, H.PILLNAME, H.CUSTOMDESCRIPTION, H.tz_secs, H.tz_name, H.dosageType, H.managedDescription, H.OPID, H.DELETED, H.GUID, H.UPDATEUSERID, H.CREATIONDATE, H.OPERATION, H.EVENTDESCRIPTION, H.SCHEDULEDATE, H.EDITTIME, H.PERSONID, H.OPERATIONDATA, H.CREATEUSERID, HP.startDate, HP.endDate, HP.scheduleFrequency, HP.dayPeriod, HP.weekdays, HP.scheduleChoice, HP.isPostponedEventActive, HP.finalPostponedDateTime, HP.actionDate, HP.recordDate, HP.scheduleGuid FROM PILL_HISTORY H JOIN HISTORY_PREFERENCE HP  WHERE H.GUID = HP.GUID AND " + HISTORY_EVENT_OPERATION + "= ? COLLATE NOCASE AND "+ PILL_ID + "= ?  ORDER BY DATETIME(H.SCHEDULEDATE) DESC ";

	public static final String GET_RECENT_POSTPONE_HISTORY_EVENT_FOR_PILLID_AND_TIME = "SELECT H.PILLID, H.PILLNAME, H.CUSTOMDESCRIPTION, H.tz_secs, H.tz_name, H.dosageType, H.managedDescription, H.OPID, H.DELETED, H.GUID, H.UPDATEUSERID, H.CREATIONDATE, H.OPERATION, H.EVENTDESCRIPTION, H.SCHEDULEDATE, H.EDITTIME, H.PERSONID, H.OPERATIONDATA, H.CREATEUSERID, HP.startDate, HP.endDate, HP.scheduleFrequency, HP.dayPeriod, HP.weekdays, HP.scheduleChoice, HP.isPostponedEventActive, HP.finalPostponedDateTime, HP.actionDate, HP.recordDate, HP.scheduleGuid FROM PILL_HISTORY H JOIN HISTORY_PREFERENCE HP  WHERE H.GUID = HP.GUID AND " + HISTORY_EVENT_OPERATION + "= ? COLLATE NOCASE AND "+ PILL_ID + "= ? AND DATETIME(H.SCHEDULEDATE) <= DATETIME(?) ORDER BY DATETIME(H.SCHEDULEDATE) DESC LIMIT 1";


	public static final String GET_HISTORY_GUID ="select "+ HISTORY_EVENT_GUID +" from "+ HISTORY_TABLE +" where "+ PILL_ID +" =? AND "+HISTORY_EVENT_SCHEDULE_DATE+ " =?";

	// scheduleGUID upgrade queries
	public static final String CREATE_TABLE_PILL_NEW_QUERY = "CREATE TABLE IF NOT EXISTS PILL_NEW (_id integer primary key, PILLID VARCHAR(300) unique, USERID VARCHAR(300), PILLNAME VARCHAR(300), CREATED VARCHAR(300), DAYPERIOD VARCHAR(300), DOSE VARCHAR(300), NUMPILLS VARCHAR(300), INSTRUCTION VARCHAR(300), HASUNDO VARCHAR(300), LAST_TAKEN VARCHAR(300), EFFLASTTAKEN VARCHAR(300), NEXT VARCHAR(300), OVERDUE VARCHAR(300), START VARCHAR(300), END VARCHAR(300), NOTIFYAFTER VARCHAR(300), TAKEPILLAFTER VARCHAR(300), SKIPPILLAFTER VARCHAR(300), MAXPOSTPONETIME VARCHAR(300), SERVEREDITTIME VARCHAR(300), SERVEREDITGUID VARCHAR(300), INSTRUCTIONS VARCHAR(300), INTERVAL VARCHAR(300), NOTIFYAFTER_TZSECS VARCHAR(300),LAST_TAKEN_TZSECS VARCHAR(300), EFFLASTTAKEN_TZSECS VARCHAR(300), SCHEDULE_GUID VARCHAR(200));";
	public static final String ALTER_TABLE_RENAME_PILL = "ALTER TABLE PILL_NEW RENAME TO PILL;";
	public static final String ALTER_TABLE_INSERT_PILL = "INSERT INTO PILL_NEW (PILLID, USERID, PILLNAME, CREATED, DAYPERIOD, DOSE, NUMPILLS, INSTRUCTION, HASUNDO, LAST_TAKEN, EFFLASTTAKEN, NEXT, OVERDUE, START, END, NOTIFYAFTER, TAKEPILLAFTER, SKIPPILLAFTER, MAXPOSTPONETIME, SERVEREDITTIME, SERVEREDITGUID, INSTRUCTIONS, INTERVAL, NOTIFYAFTER_TZSECS, LAST_TAKEN_TZSECS, EFFLASTTAKEN_TZSECS) " +
			"SELECT PILLID, USERID, PILLNAME, CREATED, DAYPERIOD, DOSE, NUMPILLS, INSTRUCTION, HASUNDO, LAST_TAKEN, EFFLASTTAKEN, NEXT, OVERDUE, START, END, NOTIFYAFTER, TAKEPILLAFTER, SKIPPILLAFTER, MAXPOSTPONETIME, SERVEREDITTIME, SERVEREDITGUID, INSTRUCTIONS, INTERVAL, NOTIFYAFTER_TZSECS, LAST_TAKEN_TZSECS, EFFLASTTAKEN_TZSECS FROM PILL;";

	public static final String CHECK_HISTORY_EVENT_COUNT_FOR_ORIGINAL_SCH_TIME = "select count(ph.PILLID) as EventCount from PILL_HISTORY ph where ph.SCHEDULEDATE = '%s' and ph.PILLID = '%s' AND (ph.OPERATION != 'EMPTY' AND ph.OPERATION !='" + PillpopperConstants.ACTION_POSTPONE_PILL_HISTORY + "') ";

}